name: Build a draft release

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Retrieve version from VERSION
        run: |
          RELVER=$(cat VERSION | tr -d '[:space:]')
          echo "RELVER=$RELVER" >> $GITHUB_ENV

      - name: Retrieve app name from APPNAME
        run: |
          APPNAME=$(cat APPNAME)
          echo "APPNAME=$APPNAME" >> $GITHUB_ENV
        
      - name: Draft a release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELVER }}
          body: |
            **!Important - review then remove this top section**

            - [ ] Verify the .sql and .qvf are correct
            - [ ] Align the tag to the release version
            - [ ] Verify release name matches tag (e.g. v1.2.1)
            - [ ] Add any comments on breaking changes/ amends to the auto generated release notes
            - [ ] Delete this section

            We are pleased to release version ${{ env.RELVER }} of the ${{ env.APPNAME }}.

            Find attached the app (${{ env.APPNAME }}.qvf) and SQL to create the required warehouse (${{ env.APPNAME }}.sql).

            The following changes have been made for this release:
            - Change 1
            - Change 2
            
          draft: true
          tag_name: ${{ env.RELVER }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ./app/${{ env.APPNAME }}.qvf
            ./resources/${{ env.APPNAME }}.sql
            